heat_template_version: 2013-05-23

description: >
  This is an HA environment for Chef Server 12.
  This will install everything that is required
  for http://docs.chef.io/install_server_ha_drbd.html

parameters:
  key_name:
    type: string
    label: key_name
    description: Name of key-pair to be used for compute instance
    default: jdizzle
  image_id:
    type: string
    label: image_id
    description: Name of the image to use for compute instance
    default: ubuntu-trusty
  instance_type:
    type: string
    label: instance_type
    description: Type of instance (flavor) to be used
    default: m1.medium
    constraints:
      - allowed_values: [ m1.medium, m1.large, m1.xlarge ]
        description: Value must be m1.medium, m1.large, or m1.xlarge
  public_net:
    type: string
    description: public network id
  secgroup_id:
    type: string
    description : Id of the security groupe


resources:
  private_net:
        type: OS::Neutron::Net
        properties:
          name: private-net

  private_subnet:
        type: OS::Neutron::Subnet
        properties:
          network_id: { get_resource: private_net }
          cidr: 172.16.2.0/24
          gateway_ip: 172.16.2.1

  chefrouter:
        type: OS::Neutron::Router
        properties:
          external_gateway_info:
            network: { get_param: public_net }

  chefrouter_interface:
        type: OS::Neutron::RouterInterface
        properties:
          router_id: { get_resource: chefrouter }
          subnet_id: { get_resource: private_subnet }

  chefserver-be1_port:
        type: OS::Neutron::Port
        properties:
          network_id: { get_resource: private_net }
          security_groups: [ get_param: secgroup_id ]
          fixed_ips:
            - subnet_id: { get_resource: private_subnet }

  chefserver-be1_floating_ip:
        type: OS::Neutron::FloatingIP
        properties:
          floating_network_id: { get_param: public_net }
          port_id: { get_resource: chefserver-be1_port }

  chefserver-be2_port:
        type: OS::Neutron::Port
        properties:
          network_id: { get_resource: private_net }
          security_groups: [ get_param: secgroup_id ]
          fixed_ips:
            - subnet_id: { get_resource: private_subnet }

  chefserver-be2_floating_ip:
        type: OS::Neutron::FloatingIP
        properties:
          floating_network_id: { get_param: public_net }
          port_id: { get_resource: chefserver-be2_port }

  chefserver-be1:
        type: OS::Nova::Server
        properties:
          name: chefserver-be1
          image: { get_param: image_id }
          flavor: m1.medium
          networks:
                - port: { get_resource: chefserver-be1_port }

  chefserver-be2:
        type: OS::Nova::Server
        properties:
          name: chefserver-be2
          image: { get_param: image_id }
          flavor: m1.medium
          networks:
            - port: { get_resource: chefserver-be2_port }

outputs:
  chefserver-be1_private_ip:
    description: Private IP address of chefserver-be1
    value: { get_attr: [ chefserver-be1, first_address ] }
  chefserver-be1_public_ip:
    description: Floating IP address of chefserver-be1
    value: { get_attr: [ chefserver-be1_floating_ip, floating_ip_address ] }
  chefserver-be2_private_ip:
    description: Private IP address of chefserver-be2
    value: { get_attr: [ chefserver-be1, first_address ] }
  chefserver-be2_public_ip:
    description: Floating IP address of chefserver-be2
    value: { get_attr: [ chefserver-be2_floating_ip, floating_ip_address ] }
