heat_template_version: 2013-05-23

description: >
  This is an Standalone environment for Chef Server 12.
  This will install everything that is required
  for http://docs.chef.io/install_server.html

parameters:
  chefserver-core:
    type: string
    label: chefserver-core
    description: The chef server core version to pull down
    default: chef-server-core_12.1.2-1_amd64.deb
  chefserver-username:
    type: string
    label: chefserver-username
    description: The first username for chef server
    default: admin
  chefserver-firstname:
    type: string
    label: chefserver-firstname
    description: The first name for chef server username
    default: Admin
  chefserver-lastname:
    type: string
    label: chefserver-lastname
    description: The last name for chef server username
    default: Jacob
  chefserver-email:
    type: string
    label: chefserver-email
    description: The email for chef server username
    default: admin@fake-email.org
  chefserver-password:
    type: string
    label: chefserver-password
    description: The password for chef server username
    default: 123456
  chefserver-shortname:
    type: string
    label: chefserver-shortname
    description: The short name for chef server org
    default: defaultinc
  chefserver-fullname:
    type: string
    label: chefserver-fullname
    description: The full name for chef server org
    default: "Default Inc"
  key_name:
    type: string
    label: key_name
    description: Name of key-pair to be used for compute instance
    default: admin
  image_id:
    type: string
    label: image_id
    description: Name of the image to use for compute instance
    default: centos-6.5
  instance_type:
    type: string
    label: instance_type
    description: Type of instance (flavor) to be used
    default: m1.medium
    constraints:
      - allowed_values: [ m1.medium, m1.large, m1.xlarge ]
        description: Value must be m1.medium, m1.large, or m1.xlarge
  public_net:
    type: string
    description: public network id
  tenant_net:
    type: string
    description: tenant network id
  tenant_subnet:
    type: string
    description: tenant subnet id

resources:

  securitygroup:
    type: OS::Neutron::SecurityGroup
    properties:
      name: chefserver-securitygroup
      description: chefserver security group
      rules:
      - {remote_ip_prefix: 0.0.0.0/0, port_range_min: 22, protocol: tcp, port_range_max: 22}
      - {remote_ip_prefix: 0.0.0.0/0, port_range_min: 80, protocol: tcp, port_range_max: 80}
      - {remote_ip_prefix: 0.0.0.0/0, port_range_min: 443, protocol: tcp, port_range_max: 443}

  chefserver_port:
        type: OS::Neutron::Port
        properties:
          network_id: { get_param: tenant_net }
          security_groups: [ {Ref: securitygroup} ]
          fixed_ips:
            - subnet_id: { get_param: tenant_subnet }

  chefserver_floating_ip:
        type: OS::Neutron::FloatingIP
        properties:
          floating_network_id: { get_param: public_net }
          port_id: { get_resource: chefserver_port }

  chefserver:
        type: OS::Nova::Server
        properties:
          name: chefserver
          key_name: { get_param: key_name }
          image: { get_param: image_id }
          flavor: { get_param: instance_type }
          admin_user: centos
          networks:
            - port: { get_resource: chefserver_port }
          user_data:
            str_replace:
              template: |
                #!/bin/bash
                echo "127.0.0.1  chefserver  chefserver" >> /etc/hosts
                curl -s https://packagecloud.io/install/repositories/chef/stable/script.rpm.sh | bash
                yum install -y chef-server-core-12.2.0-1.el6.x86_64
                chef-server-ctl reconfigure
                yum install -y chef-marketplace-0.0.2-1.el6.x86_64
                mkdir /etc/chef-marketplace
                echo "topology 'chef-marketplace'" >> /etc/opscode/chef-server.rb
                echo "license['nodes'] = 25" >> /etc/opscode/chef-server.rb
                echo "support['email'] = 'admin@chef.io'" >> /etc/chef-marketplace/marketplace.rb
                echo "documentation['url'] = 'docs.chef.io'" >> /etc/chef-marketplace/marketplace.rb
                echo "role 'aio'" >> /etc/chef-marketplace/marketplace.rb
                echo "platform 'openstack'" >> /etc/chef-marketplace/marketplace.rb
                echo "user 'openstack-user'" >> /etc/chef-marketplace/marketplace.rb
                echo "disable_outboud_traffic false" >> /etc/chef-marketplace/marketplace.rb
                chef-marketplace-ctl reconfigure
                chef-marketplace-ctl setup -f $chef_server_firstname -l $chef_server_lastname -e $chef_server_email -o $chef_server_shortname -u $chef_server_username -p $chef_server_password -y
                chef-marketplace-ctl upgrade -y

              params:
                $chef_server_version: { get_param: chefserver-core }
                $chef_server_username: { get_param: chefserver-username }
                $chef_server_firstname: { get_param: chefserver-firstname }
                $chef_server_lastname: { get_param: chefserver-lastname }
                $chef_server_email: { get_param: chefserver-email }
                $chef_server_password: { get_param: chefserver-password }
                $chef_server_shortname: { get_param: chefserver-shortname }
                $chef_server_full: { get_param: chefserver-fullname }

outputs:
  chefserver_private_ip:
    description: Private IP address of chefserver
    value: { get_attr: [ chefserver, first_address ] }
  chefserver_public_ip:
    description: Floating IP address of chefserver
    value: { get_attr: [ chefserver_floating_ip, floating_ip_address ] }
